apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-api
  labels:
    app.kubernetes.io/name: symfony-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: symfony-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: symfony-api
    spec:
      containers:
        - name: symfony-api
          image: observability-symfony-api:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: APP_ENV
              value: prod
            - name: APP_DEBUG
              value: "0"
            - name: APP_SECRET
              value: local-dev-secret

            - name: DOWNSTREAM_URL
              value: http://laravel-api/chain
            - name: PUBLISH_URL
              value: http://laravel-api/publish

            - name: OTEL_SERVICE_NAME
              value: symfony-api
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=0.1.0,deployment.environment=local
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
