apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-api
  labels:
    app.kubernetes.io/name: laravel-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: laravel-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: laravel-api
    spec:
      containers:
        - name: laravel-api
          image: observability-laravel-api:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: APP_NAME
              value: laravel-api
            - name: APP_ENV
              value: local
            - name: APP_DEBUG
              value: "true"
            - name: APP_KEY
              value: base64:aMV4nQ4ZqXhK8RJ67NRHpSI1W60hmEPfG9mMWCN65sY=
            - name: LOG_CHANNEL
              value: stderr
            - name: SESSION_DRIVER
              value: array

            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: app
            - name: DB_USERNAME
              value: app
            - name: DB_PASSWORD
              value: app

            - name: DOWNSTREAM_URL
              value: http://fastapi/sleep

            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: app
            - name: RABBITMQ_PASS
              value: app
            - name: RABBITMQ_QUEUE
              value: observability

            - name: OTEL_SERVICE_NAME
              value: laravel-api
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=0.1.0,deployment.environment=local
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
