apiVersion: v1
kind: Service
metadata:
  name: laravel-api
  labels:
    app.kubernetes.io/name: laravel-api
spec:
  selector:
    app.kubernetes.io/name: laravel-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
